// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: capacity.proto

package capacity_print;

public final class capacityImpl {
  private capacityImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_capacity_printRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_capacity_printRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_capacity_printResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_capacity_printResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_capacity_storageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_capacity_storageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_capacity_storageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_capacity_storageResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016capacity.proto\022\010capacity\"\035\n\014printReque" +
      "st\022\r\n\005print\030\001 \001(\010\"!\n\rprintResponse\022\020\n\010pr" +
      "inting\030\001 \001(\t\"4\n\016storageRequest\022\"\n\007storag" +
      "e\030\001 \001(\0162\021.capacity.Storage\"&\n\017storageRes" +
      "ponse\022\023\n\013new_storage\030\001 \001(\t**\n\007Storage\022\t\n" +
      "\005BASIC\020\000\022\n\n\006SILVER\020\001\022\010\n\004GOLD\020\0022\221\001\n\017capac" +
      "ityService\022<\n\005print\022\026.capacity.printRequ" +
      "est\032\027.capacity.printResponse\"\0000\001\022@\n\007stor" +
      "age\022\030.capacity.storageRequest\032\031.capacity" +
      ".storageResponse\"\000B \n\016capacity_printB\014ca" +
      "pacityImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_capacity_printRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_capacity_printRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_capacity_printRequest_descriptor,
        new java.lang.String[] { "Print", });
    internal_static_capacity_printResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_capacity_printResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_capacity_printResponse_descriptor,
        new java.lang.String[] { "Printing", });
    internal_static_capacity_storageRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_capacity_storageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_capacity_storageRequest_descriptor,
        new java.lang.String[] { "Storage", });
    internal_static_capacity_storageResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_capacity_storageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_capacity_storageResponse_descriptor,
        new java.lang.String[] { "NewStorage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
