// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: capacity.proto

package capacity_print;

public interface storageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:capacity.storageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.capacity.Storage storage = 1;</code>
   */
  int getStorageValue();
  /**
   * <code>.capacity.Storage storage = 1;</code>
   */
  capacity_print.Storage getStorage();
}
