// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: capacity.proto

package capacity_print;

public interface storageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:capacity.storageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string new_storage = 1;</code>
   */
  java.lang.String getNewStorage();
  /**
   * <code>string new_storage = 1;</code>
   */
  com.google.protobuf.ByteString
      getNewStorageBytes();
}
