// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: capacity.proto

package capacity_print;

/**
 * <pre>
 * Storage will be requested by the client, who wants to choose a new size among the 3 options. 
 * </pre>
 *
 * Protobuf type {@code capacity.storageRequest}
 */
public  final class storageRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:capacity.storageRequest)
    storageRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use storageRequest.newBuilder() to construct.
  private storageRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private storageRequest() {
    storage_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private storageRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            storage_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return capacity_print.capacityImpl.internal_static_capacity_storageRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return capacity_print.capacityImpl.internal_static_capacity_storageRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            capacity_print.storageRequest.class, capacity_print.storageRequest.Builder.class);
  }

  public static final int STORAGE_FIELD_NUMBER = 1;
  private int storage_;
  /**
   * <code>.capacity.Storage storage = 1;</code>
   */
  public int getStorageValue() {
    return storage_;
  }
  /**
   * <code>.capacity.Storage storage = 1;</code>
   */
  public capacity_print.Storage getStorage() {
    @SuppressWarnings("deprecation")
    capacity_print.Storage result = capacity_print.Storage.valueOf(storage_);
    return result == null ? capacity_print.Storage.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (storage_ != capacity_print.Storage.BASIC.getNumber()) {
      output.writeEnum(1, storage_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (storage_ != capacity_print.Storage.BASIC.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, storage_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof capacity_print.storageRequest)) {
      return super.equals(obj);
    }
    capacity_print.storageRequest other = (capacity_print.storageRequest) obj;

    boolean result = true;
    result = result && storage_ == other.storage_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STORAGE_FIELD_NUMBER;
    hash = (53 * hash) + storage_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static capacity_print.storageRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static capacity_print.storageRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static capacity_print.storageRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static capacity_print.storageRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static capacity_print.storageRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static capacity_print.storageRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static capacity_print.storageRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static capacity_print.storageRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static capacity_print.storageRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static capacity_print.storageRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static capacity_print.storageRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static capacity_print.storageRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(capacity_print.storageRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Storage will be requested by the client, who wants to choose a new size among the 3 options. 
   * </pre>
   *
   * Protobuf type {@code capacity.storageRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:capacity.storageRequest)
      capacity_print.storageRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return capacity_print.capacityImpl.internal_static_capacity_storageRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return capacity_print.capacityImpl.internal_static_capacity_storageRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              capacity_print.storageRequest.class, capacity_print.storageRequest.Builder.class);
    }

    // Construct using capacity_print.storageRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      storage_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return capacity_print.capacityImpl.internal_static_capacity_storageRequest_descriptor;
    }

    @java.lang.Override
    public capacity_print.storageRequest getDefaultInstanceForType() {
      return capacity_print.storageRequest.getDefaultInstance();
    }

    @java.lang.Override
    public capacity_print.storageRequest build() {
      capacity_print.storageRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public capacity_print.storageRequest buildPartial() {
      capacity_print.storageRequest result = new capacity_print.storageRequest(this);
      result.storage_ = storage_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof capacity_print.storageRequest) {
        return mergeFrom((capacity_print.storageRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(capacity_print.storageRequest other) {
      if (other == capacity_print.storageRequest.getDefaultInstance()) return this;
      if (other.storage_ != 0) {
        setStorageValue(other.getStorageValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      capacity_print.storageRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (capacity_print.storageRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int storage_ = 0;
    /**
     * <code>.capacity.Storage storage = 1;</code>
     */
    public int getStorageValue() {
      return storage_;
    }
    /**
     * <code>.capacity.Storage storage = 1;</code>
     */
    public Builder setStorageValue(int value) {
      storage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.capacity.Storage storage = 1;</code>
     */
    public capacity_print.Storage getStorage() {
      @SuppressWarnings("deprecation")
      capacity_print.Storage result = capacity_print.Storage.valueOf(storage_);
      return result == null ? capacity_print.Storage.UNRECOGNIZED : result;
    }
    /**
     * <code>.capacity.Storage storage = 1;</code>
     */
    public Builder setStorage(capacity_print.Storage value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      storage_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.capacity.Storage storage = 1;</code>
     */
    public Builder clearStorage() {
      
      storage_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:capacity.storageRequest)
  }

  // @@protoc_insertion_point(class_scope:capacity.storageRequest)
  private static final capacity_print.storageRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new capacity_print.storageRequest();
  }

  public static capacity_print.storageRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<storageRequest>
      PARSER = new com.google.protobuf.AbstractParser<storageRequest>() {
    @java.lang.Override
    public storageRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new storageRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<storageRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<storageRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public capacity_print.storageRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

