// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: capacity.proto

package print;

public interface printResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:capacity.printResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string printing = 1;</code>
   */
  java.lang.String getPrinting();
  /**
   * <code>string printing = 1;</code>
   */
  com.google.protobuf.ByteString
      getPrintingBytes();
}
