// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: print.proto

package print;

public interface printRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:capacity.printRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool print = 1;</code>
   */
  boolean getPrint();
}
