// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: capacity.proto

package print;

public final class printImpl {
  private printImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_capacity_printRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_capacity_printRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_capacity_printResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_capacity_printResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016capacity.proto\022\010capacity\"\035\n\014printReque" +
      "st\022\r\n\005print\030\001 \001(\010\"!\n\rprintResponse\022\020\n\010pr" +
      "inting\030\001 \001(\t2L\n\014printService\022<\n\005print\022\026." +
      "capacity.printRequest\032\027.capacity.printRe" +
      "sponse\"\0000\001B\024\n\005printB\tprintImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_capacity_printRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_capacity_printRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_capacity_printRequest_descriptor,
        new java.lang.String[] { "Print", });
    internal_static_capacity_printResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_capacity_printResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_capacity_printResponse_descriptor,
        new java.lang.String[] { "Printing", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
