// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cloud.proto

package CloudManagment;

public interface AddRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CloudManagment.AddRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string empNo = 1;</code>
   */
  java.lang.String getEmpNo();
  /**
   * <code>string empNo = 1;</code>
   */
  com.google.protobuf.ByteString
      getEmpNoBytes();

  /**
   * <code>string dateOfBirth = 2;</code>
   */
  java.lang.String getDateOfBirth();
  /**
   * <code>string dateOfBirth = 2;</code>
   */
  com.google.protobuf.ByteString
      getDateOfBirthBytes();

  /**
   * <code>string firstName = 3;</code>
   */
  java.lang.String getFirstName();
  /**
   * <code>string firstName = 3;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string lastName = 4;</code>
   */
  java.lang.String getLastName();
  /**
   * <code>string lastName = 4;</code>
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>string gender = 5;</code>
   */
  java.lang.String getGender();
  /**
   * <code>string gender = 5;</code>
   */
  com.google.protobuf.ByteString
      getGenderBytes();

  /**
   * <code>string hireDate = 6;</code>
   */
  java.lang.String getHireDate();
  /**
   * <code>string hireDate = 6;</code>
   */
  com.google.protobuf.ByteString
      getHireDateBytes();
}
