// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cloud.proto

package CloudManagment;

public interface RemoveRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CloudManagment.RemoveRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 empNo = 1;</code>
   */
  int getEmpNo();

  /**
   * <code>string firstName = 2;</code>
   */
  java.lang.String getFirstName();
  /**
   * <code>string firstName = 2;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();
}
